service: greyhound-alexa-skill

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
#  include:
#    - include-me.py
#    - include-me-dir/**
  exclude:
    - __pycache__/**
    - .cache/**
    - env/**
    - tests/**
    - handler.pyc
    - intents.json
    - LICENSE
    - list_of_foods.txt
    - README.md
    - requirements.txt
    - sample_utterances.txt

functions:
  hello:
    handler: handler.hello
    events:
      - alexaSkill

#    Define function environment variables here
#    environment:
#      variable2: value2
